### ISSUE TITLE
Mailbox Plante on reset filter

### ISSUE THREAD

**Issue by ocyssau** [ocyssau/rbplm3#30]
File:

    /usr/share/ranchbe/rbsier/vendor/zendframework/zend-form/src/Form.php:540

Message:

    Zend\Form\Form::getData cannot return data as validation has not yet occurred

Stack trace:

    #0 /usr/share/ranchbe/rbsier/module/Application/src/Application/Form/AbstractFilterForm.php(129): Zend\Form\Form->getData()
    #1 /usr/share/ranchbe/rbsier/module/Message/src/Message/Controller/MailboxController.php(63): Application\Form\AbstractFilterForm->save()
    #2 /usr/share/ranchbe/rbsier/vendor/zendframework/zend-mvc/src/Controller/AbstractActionController.php(82): Message\Controller\MailboxController->indexAction()
    #3 [internal function]: Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))
    #4 /usr/share/ranchbe/rbsier/vendor/zendframework/zend-eventmanager/src/EventManager.php(490): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
    #5 /usr/share/ranchbe/rbsier/vendor/zendframework/zend-eventmanager/src/EventManager.php(263): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
    #6 /usr/share/ranchbe/rbsier/vendor/zendframework/zend-mvc/src/Controller/AbstractController.php(118): Zend\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Zend\Mvc\MvcEvent))
    #7 /usr/share/ranchbe/rbsier/module/Application/src/Application/Controller/AbstractController.php(116): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response))
    #8 /usr/share/ranchbe/rbsier/vendor/zendframework/zend-mvc/src/DispatchListener.php(118): Application\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response))
    #9 [internal function]: Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
    #10 /usr/share/ranchbe/rbsier/vendor/zendframework/zend-eventmanager/src/EventManager.php(490): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
    #11 /usr/share/ranchbe/rbsier/vendor/zendframework/zend-eventmanager/src/EventManager.php(263): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
    #12 /usr/share/ranchbe/rbsier/vendor/zendframework/zend-mvc/src/Application.php(340): Zend\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Zend\Mvc\MvcEvent))
    #13 /usr/share/ranchbe/rbsier/public/index.php(105): Zend\Mvc\Application->run()
    #14 {main}

**Comment by ocyssau** [comment]
Remove call to FIlter::reset();
